# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-12-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nov_boletin_titulo', models.CharField(max_length=100)),
                ('nov_boletin_autor', models.CharField(max_length=30)),
                ('nov_boletin_fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nov_boletin_text', models.TextField(default='Por favor teclee el texto de presentación del boletín')),
                ('nov_boletin_categoria', models.CharField(max_length=30)),
                ('imagen_de_cubierta', models.ImageField(default='Suba la imagen de la cubierta', upload_to='images/')),
                ('documento_de_boletin', models.FileField(default='Suba el documento del Boletín', upload_to='boletines/')),
            ],
            options={
                'db_table': 'nov_bibliograficas_boletin',
                'verbose_name_plural': 'boletines',
                'verbose_name': 'boletin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoBoletinREcurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nov_bibliograficas_tipo_recurso',
                'verbose_name_plural': 'listado de recursos de boletin',
                'verbose_name': 'tipo de recurso',
                'managed': True,
            },
        ),
    ]
