# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades_bibliograficas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_boletin', models.CharField(default='Teclee el tipo de boletin', max_length=60)),
            ],
            options={
                'verbose_name': 'Tipo de boletin',
                'verbose_name_plural': 'Tipos de boletines',
                'db_table': 'nov_bibliograficas_tipo_boletin',
                'managed': True,
            },
        ),
    ]
