# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-16 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades_bibliograficas', '0003_boletin_tipo_boletin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletin',
            old_name='tipo_boletin',
            new_name='tipo_de_boletin_id',
        ),
    ]
