# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novedades_bibliograficas', '0004_auto_20210616_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='tipo_de_boletin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='novedades_bibliograficas.TipoBoletin'),
        ),
    ]
