# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-15 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuarios',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='1970-01-01')),
                ('hora', models.TimeField(default='01:01:00')),
                ('nombre_apellidos', models.CharField(default='Teclee el Nombre y Apellidos  del Usuario', max_length=90)),
                ('tipo_usuario', models.CharField(choices=[('ESTD', 'Estudiante'), ('PROF', 'Profesor'), ('INVEST', 'Investigador'), ('VISTEXT', 'Visitante Externo a la Institución')], default='ESTD', max_length=15)),
                ('tipo_servicio_solicitado', multiselectfield.db.fields.MultiSelectField(choices=[('Lectura en Sala', 'Lectura en Sala'), ('Busqueda de Referencia', 'Busqueda de Referencia'), ('Compilación de Información', 'Compilación de Información'), ('Busqueda Digital', 'Busqueda Digital'), ('Reprografía', 'Reprografía'), ('Busqueda de Documentos Digitales', 'Documentos Digitales')], default='Lectura en Sala', max_length=120)),
                ('institucion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacInstitucion')),
                ('recurso_prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacLibro')),
            ],
            options={
                'db_table': 'reg_usuarios',
                'verbose_name_plural': 'Registro de Usuarios Presenciales',
                'managed': True,
                'verbose_name': 'Usuario Presencial',
            },
        ),
    ]
