# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_usuarios_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousuarios',
            name='prestamo_excepcional',
            field=models.BooleanField(default=False),
        ),
    ]
