# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_usuarios_biblioteca', '0003_auto_20210630_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('ESTD', 'Estudiante'), ('NOVICIO', 'Novicio'), ('PROF', 'Profesor'), ('INVEST', 'Investigador'), ('PRESBIT', 'Presbitero'), ('TRABAJ', 'Trabajador'), ('VISTEXT', 'Visitante Externo a la Institución')], default='NOVICIO', max_length=15),
        ),
    ]
