# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-15 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpacAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(default=' ', max_length=150)),
            ],
            options={
                'db_table': 'opac_autor',
                'verbose_name_plural': 'Listado de Autores',
                'managed': True,
                'verbose_name': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='OpacCatedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_catedra', models.CharField(default=' ', max_length=60)),
                ('localizacion', models.TextField(default=' ')),
            ],
            options={
                'db_table': 'opac_catedra',
                'verbose_name_plural': 'Listado de Catedras',
                'managed': True,
                'verbose_name': 'Cátedra',
            },
        ),
        migrations.CreateModel(
            name='OpacCiudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(default=' ', max_length=50)),
            ],
            options={
                'db_table': 'opac_ciudades',
                'verbose_name_plural': 'Ciudades',
                'managed': True,
                'verbose_name': 'Ciudad',
            },
        ),
        migrations.CreateModel(
            name='OpacColeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coleccion', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'db_table': 'opac_coleccion',
                'verbose_name_plural': 'Listado de Colecciones',
                'managed': True,
                'verbose_name': 'Coleccion',
            },
        ),
        migrations.CreateModel(
            name='OpacDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_descriptor', models.CharField(default=1, max_length=100)),
                ('nombre_antiguo_descriptor', models.CharField(default=1, max_length=100)),
            ],
            options={
                'db_table': 'opac_descriptores_migration_1',
                'verbose_name_plural': 'Listado de Descriptores',
                'managed': True,
                'verbose_name': 'Descriptor',
            },
        ),
        migrations.CreateModel(
            name='OpacEditorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editorial', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'db_table': 'opac_editorial',
                'verbose_name_plural': 'Listado de Editoriales',
                'managed': True,
                'verbose_name': 'Editorial',
            },
        ),
        migrations.CreateModel(
            name='OpacIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(default=' ', max_length=40)),
            ],
            options={
                'db_table': 'opac_idioma',
                'verbose_name_plural': 'Idiomas',
                'managed': True,
                'verbose_name': 'Idioma',
            },
        ),
        migrations.CreateModel(
            name='OpacInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institución', models.CharField(max_length=70)),
                ('es_externa', models.BooleanField(default=False)),
                ('direccion_institución', models.TextField(blank=True, max_length=200, null=True)),
                ('telf_inst1', models.CharField(blank=True, max_length=13, null=True)),
                ('telf_inst2', models.CharField(blank=True, max_length=13, null=True)),
                ('fax_inst', models.CharField(blank=True, max_length=13, null=True)),
                ('email_inst', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'opac_institucion',
                'verbose_name_plural': 'Listado de Instituciones',
                'managed': True,
                'verbose_name': 'Institución',
            },
        ),
        migrations.CreateModel(
            name='OpacLibro',
            fields=[
                ('no_registro_entrada', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('título', models.CharField(default=' ', max_length=120)),
                ('subtítulo', models.CharField(default=' ', max_length=120)),
                ('numero_en_colección', models.IntegerField(default=2)),
                ('edición', models.CharField(blank=True, max_length=10, null=True)),
                ('reimpresion', models.BooleanField(default=False)),
                ('año_de_edición', models.CharField(default='', max_length=9)),
                ('paginado', models.CharField(default=' ', max_length=40)),
                ('signatura_topografica', models.CharField(default='[INF.JUV] 000 ROW H', max_length=50)),
                ('altura', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True, default=' ', null=True)),
                ('procedencia', models.CharField(default='COMPRA', max_length=20)),
                ('baja', models.BooleanField(default=False)),
                ('en_reparación', models.BooleanField(default=False)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('autor', models.ForeignKey(default=7508, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacAutor')),
                ('autor2', models.ForeignKey(blank=True, default=7508, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segundo_autor', to='opac.OpacAutor')),
                ('autor3', models.ForeignKey(blank=True, default=7508, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tercer_autor', to='opac.OpacAutor')),
            ],
            options={
                'db_table': 'opac_libro_legacy',
                'verbose_name_plural': 'Listado de Libros',
                'managed': True,
                'verbose_name': 'Libro',
            },
        ),
        migrations.CreateModel(
            name='OpacLibroCaracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_caracteristica_libro', models.CharField(default=' ', max_length=60)),
            ],
            options={
                'db_table': 'opac_libro_caracteristicas',
                'verbose_name_plural': 'Listado de Caratcerísticas de los Libros',
                'managed': True,
                'verbose_name': 'Características del Libro',
            },
        ),
        migrations.CreateModel(
            name='OpacLibroEncuadernacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuadernacion_libro', models.CharField(default=' ', max_length=60)),
            ],
            options={
                'db_table': 'opac_libro_encuadernacion',
                'verbose_name_plural': 'Listado de Encuadernaciones de los Libros',
                'managed': True,
                'verbose_name': 'Encuadernacion del Libro',
            },
        ),
        migrations.CreateModel(
            name='OpacMarc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField(blank=True, db_column='NR', null=True)),
                ('etiqueta', models.CharField(blank=True, db_column='Etiqueta', max_length=3, null=True)),
                ('tamaño', models.CharField(blank=True, db_column='Tamaño', max_length=4, null=True)),
                ('posición', models.CharField(blank=True, db_column='Posición', max_length=5, null=True)),
                ('indicador', models.CharField(blank=True, db_column='Indicador', max_length=2, null=True)),
                ('subcampo', models.CharField(blank=True, db_column='Subcampo', max_length=2, null=True)),
                ('contenido', models.CharField(blank=True, db_column='Contido', max_length=250, null=True)),
            ],
            options={
                'db_table': 'opac_marc',
                'verbose_name_plural': 'Opciones de MARC21 (A)',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OpacMarc2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rex', models.IntegerField()),
                ('sinatura', models.CharField(blank=True, max_length=20, null=True)),
                ('data_rex', models.DateTimeField(blank=True, null=True)),
                ('título', models.CharField(blank=True, max_length=120, null=True)),
                ('autor', models.CharField(blank=True, max_length=40, null=True)),
                ('autor2', models.CharField(blank=True, max_length=40, null=True)),
                ('omr', models.CharField(blank=True, max_length=40, null=True)),
                ('editorial', models.CharField(blank=True, max_length=40, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=20, null=True)),
                ('colección', models.CharField(blank=True, max_length=30, null=True)),
                ('edicion', models.CharField(blank=True, max_length=2, null=True)),
                ('lugar_impr', models.CharField(blank=True, max_length=20, null=True)),
                ('ano_impr', models.CharField(blank=True, max_length=4, null=True)),
                ('temas', models.CharField(blank=True, max_length=60, null=True)),
                ('idioma', models.CharField(blank=True, max_length=15, null=True)),
                ('soporte', models.CharField(blank=True, max_length=15, null=True)),
                ('prestado', models.NullBooleanField()),
                ('no_prestar', models.NullBooleanField()),
                ('baja', models.NullBooleanField()),
                ('listaespera', models.NullBooleanField()),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opac_marc2',
                'verbose_name_plural': 'Opciones de MARC21 (B)',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OpacMaterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(default=' ', max_length=40, verbose_name='disciplina')),
                ('descripcion_materia', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'opac_materias',
                'verbose_name_plural': 'Listado de Disciplinas',
                'managed': True,
                'verbose_name': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='OpacPais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100)),
                ('codigo_iso', models.CharField(default='ND', max_length=2)),
            ],
            options={
                'db_table': 'opac_pais',
                'verbose_name_plural': 'Listado de Paises',
                'managed': True,
                'verbose_name': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='OpacSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_soporte', models.CharField(default=' ', max_length=40)),
            ],
            options={
                'db_table': 'opac_soporte',
                'verbose_name_plural': 'Listado de Soportes de Recurso',
                'managed': True,
                'verbose_name': 'Soporte de Recurso',
            },
        ),
        migrations.CreateModel(
            name='OpacTempPrestados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, max_length=6, null=True)),
                ('ncb', models.CharField(blank=True, max_length=8, null=True)),
                ('nombrecompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('num_rex', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_devolucion', models.CharField(blank=True, max_length=10, null=True)),
                ('sinatura', models.CharField(blank=True, max_length=20, null=True)),
                ('soporte', models.CharField(blank=True, max_length=15, null=True)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'opac_temp_prestados',
                'verbose_name_plural': 'Detalles de Prestamos Temporales',
                'managed': True,
                'verbose_name': 'Detalles de Prestamo Temporal',
            },
        ),
        migrations.CreateModel(
            name='OpacTesis',
            fields=[
                ('no_reg', models.IntegerField(default=0)),
                ('signatura', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('título', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('TES', 'Tesis'), ('TESN', 'Tesina')], default='TES', max_length=10)),
                ('resumen', models.TextField()),
                ('tutor_1', models.CharField(default=' ', max_length=100)),
                ('tutor_2', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('año', models.CharField(blank=True, db_column='ano', max_length=10, null=True)),
                ('grado_aspirante', models.CharField(choices=[('DTOR', 'Doctor en Ciencias'), ('MAST', 'Master en Ciencias'), ('LICD', 'Licenciado'), ('BACH', 'Bachiller')], default='BACH', max_length=20)),
                ('palabras_clave', models.CharField(default='', max_length=200)),
                ('baja', models.NullBooleanField()),
            ],
            options={
                'db_table': 'opac_tesis',
                'verbose_name_plural': 'Listado de Tesis',
                'managed': True,
                'verbose_name': 'Tesis',
            },
        ),
        migrations.CreateModel(
            name='OpacTesisAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(default=' ', max_length=150)),
            ],
            options={
                'db_table': 'opac_tesis_autor',
                'verbose_name_plural': 'Listado de Autores de las Tesis',
                'managed': True,
                'verbose_name': 'Autor de Tesis',
            },
        ),
        migrations.CreateModel(
            name='OpacUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Teclee el nombre', max_length=25, null=True)),
                ('apellidos', models.CharField(blank=True, default='Teclee los apellidos', max_length=25, null=True)),
                ('ocupacion', models.CharField(choices=[('ESTD', 'Estudiante'), ('TRAB', 'Trabajado'), ('JUBI', 'Jubilado')], default='ESTD', max_length=15)),
                ('observaciones', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_ultimo_prestamo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opac_usuario',
                'verbose_name_plural': 'Usuarios de la Biblioteca',
                'managed': True,
                'verbose_name': 'Usuario de la Biblioteca',
            },
        ),
        migrations.AddField(
            model_name='opactesis',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor1_tesis', to='opac.OpacTesisAutor'),
        ),
        migrations.AddField(
            model_name='opactesis',
            name='autor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor2_tesis', to='opac.OpacTesisAutor'),
        ),
        migrations.AddField(
            model_name='opactesis',
            name='cátedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacCatedra'),
        ),
        migrations.AddField(
            model_name='opactesis',
            name='descriptores',
            field=models.ManyToManyField(related_name='descriptores_tesis', to='opac.OpacDescriptor'),
        ),
        migrations.AddField(
            model_name='opactesis',
            name='disciplina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacMaterias'),
        ),
        migrations.AddField(
            model_name='opactesis',
            name='institución',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institucion_tesis', to='opac.OpacInstitucion'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='caracteristicas_del_texto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacLibroCaracteristicas'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='casa_editora',
            field=models.ForeignKey(default=2782, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacEditorial'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacColeccion'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='descriptores',
            field=models.ManyToManyField(default=1, related_name='descriptores_multiples', to='opac.OpacDescriptor'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='encuadernación',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacLibroEncuadernacion'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='idioma',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='opac.OpacIdioma'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='lugar_de_edición',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='opac.OpacCiudad'),
        ),
        migrations.AddField(
            model_name='opaclibro',
            name='tipo_soporte',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacSoporte'),
        ),
        migrations.AddField(
            model_name='opaceditorial',
            name='pais_origen',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacPais'),
        ),
        migrations.AddField(
            model_name='opacciudad',
            name='nombre_pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacPais'),
        ),
    ]
