# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-16 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opaclibro',
            name='coleccion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacColeccion'),
        ),
    ]
