# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-21 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0002_auto_20210115_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpacRevsEjemplar',
            fields=[
                ('numero_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_revista', models.CharField(default='Teclee el nombre de la revista', max_length=100)),
                ('numero', models.CharField(default='teclee ', max_length=20)),
                ('ano', models.CharField(default='teclee ', max_length=20)),
                ('ISSN', models.CharField(default='Teclee la Signatura de la revista', max_length=13)),
                ('fecha', models.CharField(default='Teclee la fecha de la Revista', max_length=40)),
                ('signatura', models.CharField(default='teclee ', max_length=20)),
                ('coleccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacColeccion')),
            ],
            options={
                'db_table': 'opac_revs_ejemplar',
                'verbose_name_plural': 'Ejemplares de Revista',
                'managed': True,
                'verbose_name': 'Revista',
            },
        ),
    ]
