# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0003_opacrevsejemplar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpacRevsArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Teclee el titulo del Articulo', max_length=256)),
                ('pag_pag', models.CharField(default='Pagina a Pagina', max_length=10)),
                ('resumen', models.TextField(default='Teclee la Resena del Articulo')),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor_principal', to='opac.OpacAutor')),
                ('autor2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor_secundario', to='opac.OpacAutor')),
                ('autor3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor_tercero', to='opac.OpacAutor')),
                ('autor4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor_cuarto', to='opac.OpacAutor')),
                ('descriptores', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacDescriptor')),
                ('revista', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacRevsEjemplar')),
            ],
            options={
                'verbose_name': 'Articulo de Revista',
                'db_table': 'opac_revs_articulo',
                'verbose_name_plural': 'Articulos de la Revista',
                'managed': True,
            },
        ),
    ]
