# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0004_opacrevsarticulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opaclibro',
            name='caracteristicas_del_texto',
        ),
        migrations.AlterField(
            model_name='opaclibro',
            name='subtítulo',
            field=models.CharField(blank=True, default=' ', max_length=120, null=True),
        ),
    ]
