# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-04 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0005_auto_20210204_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpacLibroCaracteristicas',
        ),
    ]
