# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-04 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0006_delete_opaclibrocaracteristicas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opaclibro',
            old_name='encuadernación',
            new_name='tipo_de_encuadernación',
        ),
    ]
