# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-04 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0007_auto_20210204_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opaclibro',
            old_name='isbn',
            new_name='ISBN',
        ),
    ]
