# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-04 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0008_auto_20210204_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opaclibro',
            old_name='altura',
            new_name='altura_en_cm',
        ),
    ]
