# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-12 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0009_auto_20210204_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opaclibro',
            name='altura_en_cm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opaclibro',
            name='coleccion',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacColeccion'),
        ),
        migrations.AlterField(
            model_name='opaclibro',
            name='numero_en_colección',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
