# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0011_auto_20210212_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opaclibro',
            name='lugar_de_edición',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='opac.OpacCiudad'),
        ),
        migrations.AlterField(
            model_name='opacusuario',
            name='ocupacion',
            field=models.CharField(choices=[('ESTD', 'Estudiante'), ('TRAB', 'Trabajador'), ('JUBI', 'Jubilado')], default='ESTD', max_length=15),
        ),
    ]
