# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0014_auto_20210630_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opaclibro',
            name='edición',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
