# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0015_auto_20210630_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opactesis',
            name='cátedra',
        ),
    ]
