# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0017_opaclibro_numero_ejemplares_prestados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opaclibro',
            name='numero_ejemplares_prestados',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
