# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2023-03-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0018_auto_20210630_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='opaclibro',
            name='tomos',
            field=models.CharField(blank=True, default='1', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='opaclibro',
            name='coleccion',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opac.OpacColeccion'),
        ),
    ]
