# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2023-03-30 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0019_auto_20230330_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='opaclibro',
            name='numero_ejemplares',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
