# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2023-03-30 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0020_opaclibro_numero_ejemplares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opaclibro',
            name='numero_ejemplares',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opaclibro',
            name='numero_ejemplares_prestados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
